title: "Opas/OMS COVID-19"
description: "Projeto de pesquisa envolvendo instituições como HCPA, GHC, OPAS/OMS e outros hospitais."

vars:
  model_name: "covid19-cl"
  version: "1.0.0"
  corpus_pristine: "cns_hcpa.csv"
  corpus_spacy: "cns_hcpa.spacy"
  train_spacy: "train.spacy"
  dev_spacy: "dev.spacy"
  lg_model: "xlm-roberta-large"
  trf_config: "configs/base_config.cfg"
  trf_config_final: "configs/config.cfg"
  trained_model: "training/model-best"
  bucket: "shc-ai-models"

assets:
  - dest: "assets/${vars.corpus_pristine}"
    url: "s3://opas-oms/${vars.corpus_pristine}"
    description: "Notas clínicas usadas no treino"


directories: ["scripts", "configs", "assets", "packages", "training", "corpus"]

workflows:
  all:
    - create_spacy_data
    - stratify
    - fill_config
    - debug_data
    - train

commands:
  - name: "create_spacy_data"
    help: "Convert the data to spaCy's binary format"
    script:
      - "python ./scripts/convert_hcpa_cn_to_spacy.py ./assets/${vars.corpus_pristine} ./corpus/${vars.corpus_spacy}"
    outputs:
      - "corpus/${vars.corpus_spacy}"
  - name: "stratify"
    help: "Stratify data for training"
    script:
      - "python ./scripts/stratify.py ./corpus/${vars.corpus_spacy} ./corpus/${vars.train_spacy} ./corpus/${vars.dev_spacy}"
    outputs:
      - "corpus/${vars.train_spacy}"
      - "corpus/${vars.dev_spacy}"
  - name: "fill_config"
    help: "Fill base config file with environment information"
    script:
      - "python -m spacy init fill-config ${vars.trf_config} ${vars.trf_config_final}"
    outputs:
      - "${vars.trf_config_final}"
  - name: "debug_data"
    help: "Runs debug on data"
    script:
      - "python -m spacy debug data ${vars.trf_config_final}"
  - name: "train"
    help: "Train the model"
    script:
      - "python -m spacy train ${vars.trf_config_final}  --output training/ --gpu-id 0"
    outputs:
      - "${vars.trained_model}"